name: Gatsby Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current code
        uses: actions/checkout@v3

      - name: Setup the git user as the Actions user
        uses: fregante/setup-git-user@v2

      # Set up Node 14
      - name: Setup Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14.21.3
          cache: 'npm'

      # Install build tools needed for node-sass
      - name: Install build essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Install dependencies
      - name: Install packages
        run: npm install --legacy-peer-deps --no-audit
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      # Install Gatsby CLI globally with version matching your Gatsby version
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@2.12.111

      # Install gh-pages
      - name: Install gh-pages
        run: npm install -g gh-pages

      # Build and deploy
      - name: Build and Deploy
        env:
          TOKEN: ${{ secrets.token_secret_deploy }}
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          gatsby build --prefix-paths && gh-pages -d public -r https://git:$TOKEN@github.com/LinkedEarth/LeapFROGS.git