name: Gatsby Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current code
        uses: actions/checkout@v2.3.1  # Using exact version that worked

      - name: Setup the git user as the Actions user
        uses: fregante/setup-git-user@v1  # Using exact version that worked

      - name: Install Node.js
        uses: actions/setup-node@v1  # Using exact version that worked
        with:
          node-version: '14.x'

      # Clean install with exact package versions
      - name: Do a clean install of the required packages
        run: |
          rm -rf node_modules package-lock.json
          npm install --no-audit

      # Install exact Gatsby CLI version that worked
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@2.12.34

      - name: Install gh-pages
        run: npm install gh-pages -g

      - name: Build and Deploy
        env:
          TOKEN: ${{ secrets.token_secret_deploy }}
        run: |
          gatsby build --prefix-paths && gh-pages -d public -r https://git:$TOKEN@github.com/LinkedEarth/LeapFROGS.git