name: Gatsby Publish

on:
  push:
    branches:
      main
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current code
        uses: actions/checkout@v3
      - name: Setup the git user as the Actions user
        uses: fregante/setup-git-user@v2
      - name: Download nvm
        run: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
      - name: nvm setup
        run: export NVM_DIR="$HOME/.nvm"
      - name: more nvm setup
        run: [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
      - name: install node14
        run: nvm install 14
      - name: show node version
        run: nvm use 14
      - name: Do a clean install of the required packages.
        run: npm install
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli
      - name: Install the gh-pages CLI
        run: npm install gh-pages -g
      - name: Build
        env:
          TOKEN: ${{ secrets.token_secret_deploy }}
        run: |
          gatsby build --prefix-paths && gh-pages -d public -r https://git:$TOKEN@github.com/LinkedEarth/LeapFROGS.git
