name: Gatsby Publish

on:
  push:
    branches:
      main
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current code
        uses: actions/checkout@v3
      - name: Setup the git user as the Actions user
        uses: fregante/setup-git-user@v2
      - name: Download Node 14
        run: curl -sL https://deb.nodesource.com/setup_14.x -o setup_14.sh
      - name: nodesource setup
        run: sudo sh ./setup_14.sh
      - name: install node14
        run: sudo apt install nodejs
      - name: show node version
        run: node -v
      - name: Do a clean install of the required packages.
        run: npm install
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli
      - name: Install the gh-pages CLI
        run: npm install gh-pages -g
      - name: Build
        env:
          TOKEN: ${{ secrets.token_secret_deploy }}
        run: |
          gatsby build --prefix-paths && gh-pages -d public -r https://git:$TOKEN@github.com/LinkedEarth/LeapFROGS.git
