name: Gatsby Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current code
        uses: actions/checkout@v2.3.1

      - name: Setup the git user as the Actions user
        uses: fregante/setup-git-user@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'  # Using a specific version that has compatible binaries with node-sass 4.12.0

      # First install node-sass globally to ensure it's built correctly
      - name: Install node-sass globally
        run: npm install -g node-sass@4.12.0

      # Then do the regular install
      - name: Install packages
        run: npm install --no-audit

      # Install exact Gatsby CLI version
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@2.12.34

      - name: Install gh-pages
        run: npm install gh-pages -g

      - name: Build and Deploy
        env:
          TOKEN: ${{ secrets.token_secret_deploy }}
        run: |
          gatsby build --prefix-paths && gh-pages -d public -r https://git:$TOKEN@github.com/LinkedEarth/LeapFROGS.git