name: Gatsby Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current code
        uses: actions/checkout@v3

      - name: Setup the git user as the Actions user
        uses: fregante/setup-git-user@v2

      # Set up Node 16
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.2  # Using LTS version of Node 16

      # Install Gatsby CLI and gh-pages
      - name: Install Gatsby CLI and gh-pages
        run: |
          npm install -g gatsby-cli@4.25.0
          npm install -g gh-pages
          npm install -g sass

      # Remove package-lock.json and node_modules for clean install
      - name: Clean install preparation
        run: |
          rm -f package-lock.json
          rm -rf node_modules

      # Install dependencies
      - name: Do a clean install of the required packages
        run: |
          npm install --legacy-peer-deps --no-audit
          npm install sass
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      # Build and deploy
      - name: Build and Deploy
        env:
          TOKEN: ${{ secrets.token_secret_deploy }}
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          gatsby build --prefix-paths && gh-pages -d public -r https://git:$TOKEN@github.com/LinkedEarth/LeapFROGS.git