name: Gatsby Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current code
        uses: actions/checkout@v3

      - name: Setup the git user as the Actions user
        uses: fregante/setup-git-user@v2

      # Set up Node 10 directly
      - name: Setup Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14.21.3 #specific version of Node 14

      # Install specific older version of Gatsby CLI compatible with Node 10
      - name: Install Gatsby CLI and gh-pages
        run: |
          npm install -g gatsby-cli@4.25.0
          npm install -g gh-pages
          npm install -g sass    # Install sass globally

      # Install dependencies
      - name: Do a clean install of the required packages
        run: | 
          npm install --no-audit
          npm install sass      # Install sass locally in the project
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      # Build and deploy
      - name: Build and Deploy
        env:
          TOKEN: ${{ secrets.token_secret_deploy }}
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          gatsby build --prefix-paths && gh-pages -d public -r https://git:$TOKEN@github.com/LinkedEarth/LeapFROGS.git