name: Gatsby Publish

on:
  push:
    branches:
      main
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout the current code
        uses: actions/checkout@v3
      - name: Setup the git user as the Actions user
        uses: fregante/setup-git-user@v2
      - name: Install the most recent Node.js version.
        run: brew install node@16
      - name: link node.
        run: brew link node@16
      - name: start with node-gyp.
        run: npm install -g node-gyp
      - name: Do a clean install of the required packages.
        run: npm install
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@2.12.34
      - name: Install the gh-pages CLI
        run: npm install gh-pages -g
      - name: Build
        env:
          TOKEN: ${{ secrets.token_secret_deploy }}
        run: |
          gatsby build --prefix-paths && gh-pages -d public -r https://git:$TOKEN@github.com/LinkedEarth/LeapFROGS.git
